type: object
title: Scalars
properties:
  mixer:
    description: Codigo del mixer
    type: integer
    examples:
      - 2310
  plant:
    description: Codigo de la planta
    type: integer
    examples:
      - 341
  state:
    description: Tipo de Estado (ISV, POU, TJB, AJB, TPL, IYD, OSV)
    type: string
    examples:
      - TJB